baseURL = 'https://dharmablade.github.io/'
languageCode = 'ru'
title = 'Блог для проекта'
theme = "hugo-theme-nightfall"

[params]
author = "Добро пожаловать!"
user = "hello"
hostname = "dharmablade.github.io"
footerHtml = 'Матвей Журавлев, Built with <a href="https://gohugo.io" class="footerLink">Hugo</a> and <a href="https://github.com/LordMathis/hugo-theme-nightfall" class="footerLink">Nightfall</a> theme'

[menu]
  [[menu.header]]
    name = "Посты"
    weight = 0
    url = "/posts"
